var mongoose = require("mongoose");



var invoice = new mongoose.Schema({
    invoiceNo:Number,
    counter1: String,
    productName1: String,
    productPrice1: String,
    amount1:String,
    subPrice1:String,
    counter2: String,
    productName2: String,
    productPrice2: String,
    amount2:String,
    subPrice2:String,
    counter3: String,
    productName3: String,
    productPrice3: String,
    amount3:String,
    subPrice3:String,
    counter4: String,
    productName4: String,
    productPrice4: String,
    amount4:String,
    subPrice4:String,
    counter5: String,
    productName5: String,
    productPrice5: String,
    amount5:String,
    subPrice5:String,
    counter6: String,
    productName6: String,
    productPrice6: String,
    amount6:String,
    subPrice6:String,
    counter7: String,
    productName7: String,
    productPrice7: String,
    amount7:String,
    subPrice7:String,
    counter8: String,
    productName8: String,
    productPrice8: String,
    amount8:String,
    subPrice8:String,
    counter9: String,
    productName9: String,
    productPrice9: String,
    amount9:String,
    subPrice9:String,
    counter10: String,
    productName10: String,
    productPrice10: String,
    amount10:String,
    subPrice10:String,
    counter11: String,
    productName11: String,
    productPrice11: String,
    amount11:String,
    subPrice11:String,
    counter12: String,
    productName12: String,
    productPrice12: String,
    amount12:String,
    subPrice12:String,
    counter13: String,
    productName13: String,
    productPrice13: String,
    amount13:String,
    subPrice13:String,
    counter14: String,
    productName14: String,
    productPrice14: String,
    amount14:String,
    subPrice14:String,
    counter15: String,
    productName15: String,
    productPrice15: String,
    amount15:String,
    subPrice15:String,
    counter16: String,
    productName16: String,
    productPrice16: String,
    amount16:String,
    subPrice16:String,
    counter17: String,
    productName17: String,
    productPrice17: String,
    amount17:String,
    subPrice17:String,
    total:String,
    vat:String,
    toPay:String,
    customerName:String,
    customerAdd:String,
    orderAdd:String,
    customerPhone:String,
    date:String,
    
    

    created: {
        type: Date,
        default: Date.now
    }

});


//EXPORT
module.exports = mongoose.model("invoice", invoice);
